import './styles/styles.css'

import './scripts/ui.js'
import './scripts/showTip.js'
import './scripts/addtask_modal.js'
import './scripts/taskManager.js'
import './scripts/loadTasks.js'
import './scripts/editTask_modal.js'
import './scripts/showHistory_modal.js'
import './scripts/taskHistory.js'